# Staging Environment Configuration
replicaCount: 2

image:
  repository: lawfirmpro/app
  pullPolicy: IfNotPresent
  tag: "staging"

env:
  NODE_ENV: staging
  PORT: 3000
  LOG_LEVEL: info

database:
  host: "lawfirmpro-staging-db.c9w8q7x6v5b4.us-east-1.rds.amazonaws.com"
  port: 5432
  name: lawfirmpro_staging
  username: lawfirm
  ssl: true

redis:
  host: "lawfirmpro-staging-redis.abc123.0001.use1.cache.amazonaws.com"
  port: 6379
  db: 0

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  hosts:
    - host: staging.lawfirmpro.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - staging.lawfirmpro.com

monitoring:
  enabled: true

backup:
  enabled: true