# Development Environment Configuration
replicaCount: 1

image:
  repository: lawfirmpro/app
  pullPolicy: IfNotPresent
  tag: "dev"

env:
  NODE_ENV: development
  PORT: 3000
  LOG_LEVEL: debug

database:
  host: "lawfirmpro-dev-db.c9w8q7x6v5b4.us-east-1.rds.amazonaws.com"
  port: 5432
  name: lawfirmpro_dev
  username: lawfirm
  ssl: false

redis:
  host: "lawfirmpro-dev-redis.abc123.0001.use1.cache.amazonaws.com"
  port: 6379
  db: 0

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

ingress:
  enabled: false

monitoring:
  enabled: false

backup:
  enabled: false