apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lawfirmpro.fullname" . }}-uploads
  labels:
    {{- include "lawfirmpro.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: efs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lawfirmpro.fullname" . }}-logs
  labels:
    {{- include "lawfirmpro.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3